### ISSUE TITLE
Scrollbar plugin usage?

### ISSUE THREAD

**Issue by kgnfth** [windicss/plugins#2]
i added this in my config

```js
 head() {
  return {
    htmlAttrs: {
      class: `scrollbar scrollbar-thumb-blue-700 scrollbar-track-blue-300`,
    },
  }
},
```

but the scrollbar is invisible

and this is what i get in windi.css
```css
.scrollbar-thin {
  --scrollbar-track: initial;
  --scrollbar-thumb: initial;
  scrollbar-color: var(--scrollbar-thumb) var(--scrollbar-track);
  overflow: overlay;
  scrollbar-width: thin;
}
.scrollbar-thin::-webkit-scrollbar-track {
  background-color: var(--scrollbar-track);
}
.scrollbar-thin::-webkit-scrollbar-thumb {
  background-color: var(--scrollbar-thumb);
}
.scrollbar-thin::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
.scrollbar {
  --scrollbar-track: initial;
  --scrollbar-thumb: initial;
  scrollbar-color: var(--scrollbar-thumb) var(--scrollbar-track);
  overflow: overlay;
  scrollbar-width: auto;
}
.scrollbar::-webkit-scrollbar-track {
  background-color: var(--scrollbar-track);
}
.scrollbar::-webkit-scrollbar-thumb {
  background-color: var(--scrollbar-thumb);
}
.scrollbar::-webkit-scrollbar {
  width: 16px;
  height: 16px;
}
```

![image](https://user-images.githubusercontent.com/73314940/111649215-73dc5b80-8804-11eb-8913-308e68a0c575.png)
